CREATE TABLE orders (
	id SERIAL PRIMARY KEY,
	name VARCHAR(40) NOT NULL,
	created_at TIMESTAMP NOT NULL,
	est_delivery TIMESTAMP NOT NULL
	CHECK (created_at < est_delivery)
)


-- IN CHECK STATEMENT WE CAN ONLY MAKE USE OF CLOUMN INSIDE THE CHECK STATEMNETHERE WHICH WAS LOOKING AT SOME OTHER VALUE OR SOME OTHER ROW INSIDE OF OUR ORDERS TABLE ONLY THE ONE WE ARE CURRENLTY OPERATING ON.





INSERT INTO orders(name,created_at,est_delivery) VALUES ('Shirt', '2000-NOV-20 01:00AM', "2000-NOV-25 01:00AM" ) 

INSERT INTO orders(name,created_at,est_delivery) VALUES ('Shirt', '2000-NOV-20 01:00AM', '2000-NOV-20 01:00:01AM' ) 