
-- 
-- QUESTION : FIND THE NUMBER OF COMMENTS FOR EACH PHOTO WHERE THE PHOTO_ID IS LESS THAN 3 AND THE PHOTO HAS MORE THAN 2 COMMENTS

SELECT
  photo_id,
  COUNT(*)
FROM
  COMMENTS
WHERE
  photo_id < 3
GROUP BY
  photo_id
HAVING
  COUNT(*) > 2






-- QUESTION : FIND THE USERS (USER_IDS) WHERE THE USER HAS COMMENTED ON THE FIRST 2 PHOTOS AND THE USER ADDED MORE THAN @ COMMENTS ON THOSE PHOTOS

SELECT
  user_id,
  COUNT(user_id)
FROM
  comments
WHERE
  photo_id <= 50
GROUP BY
  user_id
HAVING
  COUNT(*) > 20